id: IBF4B5999
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T15:33:34+00:00'
last_modified: '2022-06-07T15:27:28.859889+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG25797
  title: མཚོ་སྔོན་སི་ཁྲོན་ཀན་སུའུ་ཡུན་ནན་ཞིང་ཆེན་བཞིའི་བོད་ཁུལ་གྱི་དགོན་སྡེ་དང་རི་ཆུའི་མིང་རྒྱ་བོད་ཤན་སྦྱར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    DE11:
      image_group_id: I1KG25799
      title: ''
      total_pages: 687
      order: 1
      base_file: DE11.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
