id: P002900
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG25797
  title: མཚོ་སྔོན་སི་ཁྲོན་ཀན་སུའུ་ཡུན་ནན་ཞིང་ཆེན་བཞིའི་བོད་ཁུལ་གྱི་དགོན་སྡེ་དང་རི་ཆུའི་མིང་རྒྱ་བོད་ཤན་སྦྱར།
  author: ''
  volumes: {}
