id: P002900
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG25797
  title: མཚོ་སྔོན་སི་ཁྲོན་ཀན་སུའུ་ཡུན་ནན་ཞིང་ཆེན་བཞིའི་བོད་ཁུལ་གྱི་དགོན་སྡེ་དང་རི་ཆུའི་མིང་རྒྱ་བོད་ཤན་སྦྱར།
  author: ''
  volumes:
    55b540a8f355486f8a0677a2a38166c3:
      image_group_id: I1KG25799
      title: ''
      volume_number: 1
      total_pages: 687
